POST http://localhost:8000/fichas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQ0MTkyNzYzfQ.cXvw3UT_i5NpRjZm_EmVD8cRI03Y1Y8BUUulROqlF9E

{
    "codigo_ficha":"1414",
    "fecha_inicio":"2022-09-08",
    "programa_idprograma":1,
    "estado_ficha_idestado_ficha":1

}

###
PUT http://localhost:8000/fichas/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQ0MTkyNzYzfQ.cXvw3UT_i5NpRjZm_EmVD8cRI03Y1Y8BUUulROqlF9E

{
    "codigo_ficha":"25254",
    "fecha_inicio":"2025-09-08",
    "programa_idprograma":1,
    "estado_ficha_idestado_ficha":1

}
###
POST http://localhost:8000/filtroFP
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlcyI6Ik1hcmNvIEFudG9uaW8iLCJyb2xlcyI6WyJJbnN0cnVjdG9yIl0sImV4cCI6MTc0NDA2NzQyOX0.c1TZAw8rRgiuqvmABLeJZ_Im7ykRTLCR3q_RoRpo4ZE

{
  "fechaInicio": "2025-04-01",
  "fechaFin": "2025-04-02",
  "idPrograma": 1
}

###
GET http://localhost:8000/aprendices-por-ficha?idFicha=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlcyI6Ik1hcmNvIEFudG9uaW8iLCJyb2xlcyI6WyJJbnN0cnVjdG9yIl0sImV4cCI6MTc0NDExNzMxMH0.qMVOP_eQ5QZtPxoZEtJ-x1ApRTVOmqBpkVSmbvK2oC4

###
GET http://localhost:8000/fichas-instructor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlcyI6Ik1hcmNvIEFudG9uaW8iLCJyb2xlcyI6WyJJbnN0cnVjdG9yIl0sImV4cCI6MTc0NDExNzMxMH0.qMVOP_eQ5QZtPxoZEtJ-x1ApRTVOmqBpkVSmbvK2oC4

###
POST http://localhost:8000/misAprendices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlcyI6Ik1hcmNvIEFudG9uaW8iLCJyb2xlcyI6WyJJbnN0cnVjdG9yIl0sImV4cCI6MTc0NDA2NzQyOX0.c1TZAw8rRgiuqvmABLeJZ_Im7ykRTLCR3q_RoRpo4ZE

{
  "idAprendiz": 2
}
###
GET http://localhost:8000/tipoAsistencia
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlcyI6Ik1hcmNvIEFudG9uaW8iLCJyb2xlcyI6WyJJbnN0cnVjdG9yIl0sImV4cCI6MTc0MzgzODY0NX0.TtDPPPTveLdUzpaLK1tNC5Mta6vnkeYWZp_12ILhu1A

### Asignar un instructor a una ficha
POST http://localhost:8000/asignarAIF
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQzNzk0NTc0fQ.9jgZnoo6-dcbPC74x2Gj80NQrwJk6hIDQvfZnFA-bWs

{
  "idFuncionario": 1,
  "idFicha": 1
}

###
GET http://localhost:8000/instructoresAIF
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlcyI6Ik1hcmNvIEFudG9uaW8iLCJyb2xlcyI6WyJJbnN0cnVjdG9yIl0sImV4cCI6MTc0MzgwNTI2N30.__3QBu6SCHDhlh98Jd7w6ED0es705CIWz8VcNZCIumI
###
GET http://localhost:8000/fichaAIF
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQzNzIwOTgzfQ.kQdPDvfdU92J18N6U4bPBs0L8VMmXXpJRutGXQB_PnI
  
###
POST http://localhost:8000/login/funcionario
Content-Type: application/json

{
  "email": "sreyesnino@gmail.com",
  "password": "1234"
}


###
POST http://localhost:8000/programa
Content-Type:application/json

{
   
  "codigoPrograma": 123,
  "nombrePrograma": "Prueba"

}
###
GET http://localhost:8000/programa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlcyI6Ik1hcmNvIEFudG9uaW8iLCJyb2xlcyI6WyJJbnN0cnVjdG9yIl0sImV4cCI6MTc0NDEyNDQzOX0.atxHrICcscH3qMFgexhj4HuzneyISohAfrhyTyQduC0

###
PUT http://localhost:8000/programa
Content-Type: application/json

{
  "idPrograma":3,
  "codigoPrograma": 202615,
  "nombrePrograma": "Mecatronica"
}
###
DELETE http://localhost:8000/programa/4

//CRUDS APRENDICES
###
POST http://localhost:8000/aprendiz
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQ0MjIzNjU2fQ.3MDdnkssd4xR588b6xbArn2fVM7K5sjn60suQNrtc6I
{
  
  "documento_aprendiz": "987654321",
  "nombre_aprendiz": "Lorem",
  "apellido_aprendiz": "Mitalia",
  "telefono_aprendiz": "310587455",
  "email_aprendiz": "Lorem.Mitalia@example.com",
  "password_aprendiz": "123456789",
  "ficha_idFicha": 1,
  "estado_aprendiz_idEstado_aprendiz": 5,
  "tipo_documento_idTipo_documento": 1
}

###
GET http://localhost:8000/aprendiz
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQ0MDgxNzE0fQ.o_5sRF5gEPJMA1LwbmFtInlkox_Jr-fwtglQI3GfjNU
###
PUT http://localhost:8000/aprendiz
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQ0MjIzNjU2fQ.3MDdnkssd4xR588b6xbArn2fVM7K5sjn60suQNrtc6I

{
  "idAprendiz":"8",
  "documento_aprendiz": "123456789",
  "nombre_aprendiz": "santiago",
  "apellido_aprendiz": "Reyes",
  "telefono_aprendiz": "3115336584",
  "email_aprendiz": "santiagoju.reyes@example.com",
  "password_aprendiz": "delunoaldiezf",
  "ficha_idFicha": "1",
  "estado_aprendiz_idEstado_aprendiz": "1",
  "tipo_documento_idTipo_documento": "2"
}
###
DELETE http://localhost:8000/aprendiz/1
