### Asignar un instructor a una ficha
POST http://localhost:8000/asignarAIF
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQzNzM1ODgwfQ.R_iYIOFcbtBB6EKYFspWw8FsHwTrPwVH3AkukXBvB0c

{
  "idFuncionario": 2,
  "idFicha": 1
}

###
GET http://localhost:8000/instructoresAIF
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQzNzIwOTgzfQ.kQdPDvfdU92J18N6U4bPBs0L8VMmXXpJRutGXQB_PnI
  
###
GET http://localhost:8000/fichaAIF
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQzNzIwOTgzfQ.kQdPDvfdU92J18N6U4bPBs0L8VMmXXpJRutGXQB_PnI
  
###
POST http://localhost:8000/login/funcionario
Content-Type: application/json

{
  "email": "sreyesnino@gmail.com",
  "password": "1234"
}

###
POST http://localhost:8000/programa
Content-Type:application/json

{
   
  "codigoPrograma": 123,
  "nombrePrograma": "Prueba"

}
###
GET http://localhost:8000/programa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tYnJlcyI6IlNhbnRpYWdvIEFsZWphbmRybyIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiXSwiZXhwIjoxNzQzMzE0NjYwfQ.MlKJU3NwXJtb3S9PvZ3X0nbFF3viSLmtn4jPM7LsfKY
###
PUT http://localhost:8000/programa
Content-Type: application/json

{
  "idPrograma":3,
  "codigoPrograma": 202615,
  "nombrePrograma": "Mecatronica"
}
###
DELETE http://localhost:8000/programa/4

//CRUDS APRENDICES
###
POST http://localhost:8000/aprendiz
Content-Type: application/json

{
  "documento_aprendiz": "123456789",
  "nombre_aprendiz": "Juan",
  "apellido_aprendiz": "Pérez",
  "telefono_aprendiz": "3001234567",
  "email_aprendiz": "juan.perez@example.com",
  "password_aprendiz": "password123",
  "ficha_idFicha": 1,
  "estado_aprendiz_idEstado_aprendiz": 1,
  "tipo_documento_idTipo_documento": 2
}

###
GET http://localhost:8000/aprendiz
###
PUT http://localhost:8000/aprendiz
Content-Type: application/json

{
  "idAprendiz":2,
  "documento_aprendiz": "123456789",
  "nombre_aprendiz": "santiago",
  "apellido_aprendiz": "Reyes",
  "telefono_aprendiz": "3115336584",
  "email_aprendiz": "santiago.reyes@example.com",
  "password_aprendiz": "delunoaldiezf",
  "ficha_idFicha": 1,
  "estado_aprendiz_idEstado_aprendiz": 1,
  "tipo_documento_idTipo_documento": 2
}
###
DELETE http://localhost:8000/aprendiz/1
